services:
  - type: web
    name: afs-manager
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: JWT_SECRET
        generateValue: true
